### ISSUE TITLE
NoSuchMethod ItemStackSerializer

### ISSUE THREAD

**Issue by Corenb** [GeorgH93/Minepacks#121]
### Information
**Environment information**
*Plugin + server version info*:
```
Paper-1.16
Minepacks v2.3.19-Release
```

*Online mode*: yes

*BungeeCord*: yes

**Server/crash log**
```
[11:16:56] [Server thread/INFO]: [Minepacks] Enabling Minepacks v2.3.19-Release
[11:16:56] [Server thread/INFO]: [Minepacks] [32mConfig file successfully loaded.[0m
[11:16:56] [Server thread/INFO]: [Minepacks] [32mLanguage file successfully loaded. Language: Français  Author: HiiRaZ & Sniper_TVmc[0m
[11:16:56] [Server thread/INFO]: [at.pcgf.libs.com.zaxxer.hikari.HikariDataSource] Minepacks-Connection-Pool - Starting...
[11:16:56] [Server thread/INFO]: [at.pcgf.libs.com.zaxxer.hikari.HikariDataSource] Minepacks-Connection-Pool - Start completed.
[11:16:56] [Server thread/ERROR]: Error occurred while enabling Minepacks v2.3.19-Release (Is it up to date?)
java.lang.NoSuchMethodError: 'at.pcgamingfreaks.Bukkit.ItemStackSerializer.ItemStackSerializer at.pcgamingfreaks.Bukkit.ItemStackSerializer.ItemStackSerializer.makeBukkitItemStackSerializer()'
	at at.pcgamingfreaks.Minepacks.Bukkit.Database.InventorySerializer.<clinit>(InventorySerializer.java:34) ~[?:?]
	at at.pcgamingfreaks.Minepacks.Bukkit.Database.Database.<init>(Database.java:63) ~[?:?]
	at at.pcgamingfreaks.Minepacks.Bukkit.Database.SQL.<init>(SQL.java:50) ~[?:?]
	at at.pcgamingfreaks.Minepacks.Bukkit.Database.MySQL.<init>(MySQL.java:35) ~[?:?]
	at at.pcgamingfreaks.Minepacks.Bukkit.Database.Database.getDatabase(Database.java:112) ~[?:?]
	at at.pcgamingfreaks.Minepacks.Bukkit.Minepacks.load(Minepacks.java:184) ~[?:?]
	at at.pcgamingfreaks.Minepacks.Bukkit.Minepacks.onEnable(Minepacks.java:114) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Paper-240]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Paper-240]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-240]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-240]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-240]
	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Paper-240]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[patched_1.16.3.jar:git-Paper-240]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-240]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-240]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[11:16:56] [Server thread/INFO]: [Minepacks] Disabling Minepacks v2.3.19-Release
[11:16:56] [Server thread/ERROR]: Error occurred while disabling Minepacks v2.3.19-Release (Is it up to date?)
java.lang.NullPointerException: null
	at at.pcgamingfreaks.Minepacks.Bukkit.Minepacks.unload(Minepacks.java:239) ~[?:?]
	at at.pcgamingfreaks.Minepacks.Bukkit.Minepacks.onDisable(Minepacks.java:169) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.3.jar:git-Paper-240]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.3.jar:git-Paper-240]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.3.jar:git-Paper-240]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.3.jar:git-Paper-240]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-240]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-240]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-240]
	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Paper-240]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[patched_1.16.3.jar:git-Paper-240]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-240]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-240]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by GeorgH93** [comment]
Please update your copy of the [PCGF PluginLib] (https://ci.pcgamingfreaks.at/job/PluginLib/lastSuccessfulBuild/artifact/target/PCGF_PluginLib-1.0.30-SNAPSHOT.jar).
