### ISSUE TITLE
Minepack v2.3.21 startup error - SQLite and Java 15 OpenJ9

### ISSUE THREAD

**Issue by NotQuantumRed** [GeorgH93/Minepacks#138]
Minepacks is refusing to start, but don't know what caused it since I changed a lot of things since the last time I ran the server. I updated Ubuntu to 20.10, I updated Java JRE to AdoptOpenJDK OpenJ9 (build 15.0.1+9), and updated Paper to Paper-318 from Paper-271. Here's my server log of the section regarding Minepacks. Error is not fatal, but Minepacks will not run.

[13:30:03] [Server thread/INFO]: [Minepacks] Enabling Minepacks v2.3.21-Release
[13:30:03] [Server thread/INFO]: [Minepacks] Starting Minepacks in standalone mode!
[13:30:03] [Server thread/INFO]: [Minepacks] [32mConfig file successfully loaded.[0m
[13:30:04] [Server thread/INFO]: [Minepacks] [32mLanguage file successfully loaded. Language: english  Author: GeorgH93[0m
[13:30:04] [Server thread/INFO]: [at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.HikariDataSource] Minepacks-Connection-Pool - Starting...
[13:30:04] [Server thread/ERROR]: Error occurred while enabling Minepacks v2.3.21-Release (Is it up to date?)
java.lang.NoClassDefFoundError: org.sqlite.core.NativeDB
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.System.load(Unknown Source) ~[?:?]
	at org.sqlite.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.java:274) ~[patched_1.16.4.jar:git-Paper-318]
	at org.sqlite.SQLiteJDBCLoader.extractAndLoadLibraryFile(SQLiteJDBCLoader.java:253) ~[patched_1.16.4.jar:git-Paper-318]
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:341) ~[patched_1.16.4.jar:git-Paper-318]
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:64) ~[patched_1.16.4.jar:git-Paper-318]
	at org.sqlite.core.NativeDB.load(NativeDB.java:63) ~[patched_1.16.4.jar:git-Paper-318]
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:235) ~[patched_1.16.4.jar:git-Paper-318]
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61) ~[patched_1.16.4.jar:git-Paper-318]
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28) ~[patched_1.16.4.jar:git-Paper-318]
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21) ~[patched_1.16.4.jar:git-Paper-318]
	at org.sqlite.JDBC.createConnection(JDBC.java:115) ~[patched_1.16.4.jar:git-Paper-318]
	at org.sqlite.JDBC.connect(JDBC.java:90) ~[patched_1.16.4.jar:git-Paper-318]
	at at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121) ~[?:?]
	at at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353) ~[?:?]
	at at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[?:?]
	at at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473) ~[?:?]
	at at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562) ~[?:?]
	at at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[?:?]
	at at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[?:?]
	at at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Database.ConnectionProvider.PooledConnectionProvider.init(PooledConnectionProvider.java:54) ~[?:?]
	at at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Database.ConnectionProvider.SQLiteConnectionProvider.<init>(SQLiteConnectionProvider.java:36) ~[?:?]
	at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.SQLite.<init>(SQLite.java:47) ~[?:?]
	at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.Database.getDatabase(Database.java:116) ~[?:?]
	at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Minepacks.load(Minepacks.java:192) ~[?:?]
	at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Minepacks.onEnable(Minepacks.java:116) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-318]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-318]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:469) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3150/0x00000000f97ac2d0.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: org.sqlite.core.NativeDB
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	... 41 more
[13:30:04] [Server thread/INFO]: [Minepacks] Disabling Minepacks v2.3.21-Release
[13:30:04] [Server thread/ERROR]: Error occurred while disabling Minepacks v2.3.21-Release (Is it up to date?)
java.lang.NullPointerException: null
	at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Minepacks.unload(Minepacks.java:247) ~[?:?]
	at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Minepacks.onDisable(Minepacks.java:177) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.4.jar:git-Paper-318]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.4.jar:git-Paper-318]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.4.jar:git-Paper-318]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.4.jar:git-Paper-318]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:469) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-318]
	at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3150/0x00000000f97ac2d0.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by NotQuantumRed** [comment]
Reverting to Java 14 seems to have fixed the issue. Does anyone know why this is incompatible with Java 15, or if anyone is in fact using this plugin with Java 15?

**Comment by GeorgH93** [comment]
Looks like a problem with the OpenJ9 VM, HotSpot is working fine for me.

**Comment by NotQuantumRed** [comment]
Hmm, that's really weird... Can anyone verify the repeatability of Java 15 OpenJ9 not working with this plugin?

**Comment by GeorgH93** [comment]
Looks like this is fixed with `AdoptOpenJDK OpenJ9 15.0.2+7` and `Paper-727 (MC: 1.16.5)`.
