### ISSUE TITLE
java.lang.NoSuchFieldException: COMPOSTER

### ISSUE THREAD

**Issue by ErythroCraft** [GeorgH93/Minepacks#170]
Hi.

I using your plugin on my 1.17 server.

The bp plugin is loading with an bug.

[19:22:07] [Server thread/INFO]: Minepacks-Connection-Pool - Starting...
[19:22:07] [Server thread/INFO]: Minepacks-Connection-Pool - Start completed.
[19:22:09] [Server thread/WARN]: java.lang.NoSuchFieldException: COMPOSTER
[19:22:09] [Server thread/WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2549)
[19:22:09] [Server thread/WARN]:        at at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Reflection.getField(Reflection.java:208)
[19:22:09] [Server thread/WARN]:        at at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Bukkit.NMSReflectionRemapped.getNmsField(NMSReflectionRemapped.java:123)
[19:22:09] [Server thread/WARN]:        at at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Bukkit.Util.InventoryUtils_Reflection.<clinit>(InventoryUtils_Reflection.java:84)
[19:22:09] [Server thread/WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[19:22:09] [Server thread/WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[19:22:09] [Server thread/WARN]:        at at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Bukkit.PlatformResolver.getClass(PlatformResolver.java:85)
[19:22:09] [Server thread/WARN]:        at at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Bukkit.PlatformResolver.createPlatformInstance(PlatformResolver.java:69)
[19:22:09] [Server thread/WARN]:        at at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Bukkit.PlatformResolver.createPlatformInstance(PlatformResolver.java:46)
[19:22:09] [Server thread/WARN]:        at at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Bukkit.Util.InventoryUtils.<clinit>(InventoryUtils.java:37)
[19:22:09] [Server thread/WARN]:        at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Backpack.setTitle(Backpack.java:56)
[19:22:09] [Server thread/WARN]:        at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Minepacks.load(Minepacks.java:198)
[19:22:09] [Server thread/WARN]:        at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Minepacks.onEnable(Minepacks.java:114)
[19:22:09] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[19:22:09] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[19:22:09] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[19:22:09] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495)
[19:22:09] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409)
[19:22:09] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:608)
[19:22:09] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264)
[19:22:09] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987)
[19:22:09] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
[19:22:09] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[19:22:09] [Server thread/INFO]: [Minepacks] Item name language file successfully loaded. Language: english  Author: GeorgH93
[19:22:09] [Server thread/INFO]: [Minepacks] Loading item translations ...
[19:22:09] [Server thread/INFO]: [Minepacks] Finished loading item translations for 828 items.
[19:22:09] [Server thread/INFO]: [Minepacks]  Minepacks has been enabled!  :)

**Comment by ErythroCraft** [comment]
Please, update fast.

THX

**Comment by GeorgH93** [comment]
Should already be fixed with the [v2.4.1](https://www.spigotmc.org/resources/minepacks-backpack-plugin-mc-1-7-1-17.19286/update?update=408096) update.

**Comment by ErythroCraft** [comment]
Ok. Sry.

I didn't seen.
