### ISSUE TITLE
org.sqlite.SQLiteException: [SQLITE_READONLY]  Attempt to write a readonly database (attempt to write a readonly database)

### ISSUE THREAD

**Issue by Frodwo** [GeorgH93/Minepacks#202]
[22:42:41] [Server thread/INFO]: MAGd_ issued server command: /bp
[22:42:43] [Server thread/INFO]: [QuickShop] [DEBUG] [org.maxgamer.quickshop.util.Util] [inventoryCheck] (765) Skipped plugin gui inventory check.
[22:42:44] [Craft Scheduler Thread - 52 - Minepacks/WARN]: [Minepacks] Failed to save backpack in database! Error: [SQLITE_READONLY]  Attempt to write a readonly database (attempt to write a readonly database)
[22:42:44] [Craft Scheduler Thread - 52 - Minepacks/WARN]: org.sqlite.SQLiteException: [SQLITE_READONLY]  Attempt to write a readonly database (attempt to write a readonly database)
[22:42:44] [Craft Scheduler Thread - 52 - Minepacks/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1030)
[22:42:44] [Craft Scheduler Thread - 52 - Minepacks/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1042)
[22:42:44] [Craft Scheduler Thread - 52 - Minepacks/WARN]: 	at org.sqlite.core.DB.execute(DB.java:884)
[22:42:44] [Craft Scheduler Thread - 52 - Minepacks/WARN]: 	at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:54)
[22:42:44] [Craft Scheduler Thread - 52 - Minepacks/WARN]: 	at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[22:42:44] [Craft Scheduler Thread - 52 - Minepacks/WARN]: 	at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[22:42:44] [Craft Scheduler Thread - 52 - Minepacks/WARN]: 	at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Database.DBTools.runStatement(DBTools.java:108)
[22:42:44] [Craft Scheduler Thread - 52 - Minepacks/WARN]: 	at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.SQL.lambda$saveBackpack$2(SQL.java:303)
[22:42:44] [Craft Scheduler Thread - 52 - Minepacks/WARN]: 	at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.SQL$$Lambda$10339/0x00000000df51aa10.run(Unknown Source)
[22:42:44] [Craft Scheduler Thread - 52 - Minepacks/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[22:42:44] [Craft Scheduler Thread - 52 - Minepacks/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:42:44] [Craft Scheduler Thread - 52 - Minepacks/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:42:44] [Craft Scheduler Thread - 52 - Minepacks/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:42:44] [Craft Scheduler Thread - 52 - Minepacks/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:42:44] [Craft Scheduler Thread - 52 - Minepacks/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:884)
[22:42:44] [Craft Scheduler Thread - 52 - Minepacks/INFO]: [Minepacks] Backup of the backpack has been created: /data/plugins/Minepacks/backups/MAGd__3f61578b0fcd410abefc8b5a981a23b9_1644849764058.backpack

**Comment by Frodwo** [comment]
oh I open two database with one port
