### ISSUE TITLE
Unable to query players with Chinese names

### ISSUE THREAD

**Issue by zfms4188** [GeorgH93/Minepacks#203]
### Information
**Environment information**
*Plugin + server version info*:plugin-2.3.22  server-1.7.10

```

<!-- Replace this with the output of "/backpack version". You can run the command in your console or as op ingame. -->

```

*Online mode*: yes

*BungeeCord*: yes

**Server/crash log**

```

<!-- Replace this with your crash log / link to your log file -->

```

**Plugin config (optional)**

```

<!-- Replace this with details about your config -->

```

### Details
**Description**  

use cmd：/backpack open 小明
When the player's name is in Chinese,
It will open an empty backpack.
It's like the player doesn't exist.
Whether the player being asked is online or not,
It keeps opening up an empty warehouse.
(I'm using mysql)
**Steps to reproduce**  

/backpack open 小明
**Expected behavior**  

Repair it
**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)

**Comment by GeorgH93** [comment]
Which server software (Bukkit/Spigot/Uranium/...)?
Online or offline mode?

**Comment by zfms4188** [comment]
Uranium
online

**Comment by GeorgH93** [comment]
Please try if [this build](https://ci.pcgamingfreaks.at/job/Minepacks/284/artifact/a/Minepacks-2.4.4-SNAPSHOT-Release.jar) solves the issues for you, at least for online players.
Not sure if I can do something to make offline players work, since back in the 1.7 days user names have been more restrictive and the old versions aren't handling none ascii names correctly (and even in the ascii characters are some limitations of what you were able to use).

**Comment by zfms4188** [comment]
`[14:36:23] [Server thread/ERROR]: Could not load 'plugins/Minepacks-2.4.4-SNAPSHOT-Release.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: at/pcgamingfreaks/Minepacks/Bukkit/Minepacks
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:151) ~[JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:256) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:323) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:460) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:136) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:348) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:163) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:363) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:356) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281]
Caused by: java.lang.NoClassDefFoundError: at/pcgamingfreaks/Minepacks/Bukkit/Minepacks
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_281]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_281]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:321) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:147) ~[JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]
	... 11 more
Caused by: java.lang.ClassNotFoundException: Failed to remap class at.pcgamingfreaks.Minepacks.Bukkit.Minepacks
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:683) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:604) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:343) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_281]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_281]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_281]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:321) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:147) ~[JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]
	... 11 more
Caused by: java.lang.NoClassDefFoundError: at/pcgamingfreaks/Plugin/IPlugin
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_281]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_281]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_281]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:671) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:604) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:343) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_281]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_281]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_281]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:321) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:147) ~[JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]
	... 11 more
Caused by: java.lang.ClassNotFoundException: at.pcgamingfreaks.Plugin.IPlugin
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:617) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:343) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_281]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_281]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_281]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_281]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:671) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:604) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:343) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_281]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_281]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_281]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:321) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:147) ~[JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]
	... 11 more`
error..

**Comment by GeorgH93** [comment]
I think [this](https://ci.pcgamingfreaks.at/job/Minepacks/285/artifact/a/Minepacks-2.4.4-SNAPSHOT-Release.jar) should fix it.

**Comment by zfms4188** [comment]
What to do now...  XD

**Comment by GeorgH93** [comment]
Not sure why it's not working for you.

Please try to also install [this](https://ci.pcgamingfreaks.at/job/PluginLib/lastSuccessfulBuild/artifact/target/PCGF_PluginLib-1.0.35-SNAPSHOT.jar), if it then still fails please attach the full server startup log file.
