### ISSUE TITLE
Backpacks itemstacks reset on upgrade

### ISSUE THREAD

**Issue by Vtreka** [GeorgH93/Minepacks#217]
### Help request

**Problem**
Recently did an upgrade from version 2.4.5.1-Release to 2.4.6-Release for the 1.19 update, when users log into the server the following is outputted in the server log and the contents of the backpack are reset: 

[00:31:20 WARN]: java.lang.IllegalArgumentException: argument type mismatch
[00:31:20 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:31:20 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[00:31:20 WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:31:20 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[00:31:20 WARN]: 	at at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Bukkit.ItemStackSerializer.NBTItemStackSerializer_Reflection.deserialize(NBTItemStackSerializer_Reflection.java:190)
[00:31:20 WARN]: 	at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.InventorySerializer.deserialize(InventorySerializer.java:78)
[00:31:20 WARN]: 	at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.SQL.lambda$loadBackpack$4(SQL.java:341)
[00:31:20 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82)
[00:31:20 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[00:31:20 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[00:31:20 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[00:31:20 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

Version Info:
Minepacks: 2.4.60-Release
Server: 3520-Spigot-1dffefb-b2557f6 (MC: 1.19)
Java: 17.0.3.1

**What I have tried**
Was originally tested on my admin account which had this issue. Also tested with the same result on standard member user on the server who has backpack.size.6, backpack.sort and backpack.use permissions. Tried updating Java to the latest version (version number above) with no change in behaviour.

Removed the Minepacks plugin folder so it would generate a fresh folder and database, confirmed plugin does not give errors with fresh database. If I try and update the itemstacks value of a player in the database with the value from my backup prior to upgrade it gives the above errors. I need to work out how to restore users backpack items.

**Comment by GeorgH93** [comment]
Thanks for the report.
Should be fixed with [this update](https://github.com/GeorgH93/Minepacks/releases/tag/v2.4.6.1).

**Comment by Vtreka** [comment]
Thank you, confirmed working now with no error.
