### ISSUE TITLE
[02:26:46 INFO]: [Minepacks] File "/config.yml" extracted successfully! [02:26:46 INFO]: [Minepacks] Config file successfully loaded. [02:26:46 INFO]: [Minepacks] File "/lang/en.yml" extracted successfully! [02:26:46 INFO]: [Minepacks] Language file successfully loaded. Language: english  Author: GeorgH93 [02:26:46 INFO]: [at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.HikariDataSource] Minepacks-Connection-Pool - Starting... [02:26:46 INFO]: [at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.HikariDataSource] Minepacks-Connection-Pool - Start completed. [02:26:46 INFO]: [Minepacks] File "/lang/items_en.yml" extracted successfully! [02:26:46 INFO]: [Minepacks] Item name language file successfully loaded. Language: english  Author: GeorgH93 [02:26:46 INFO]: [Minepacks] Loading item translations ... [02:26:46 INFO]: [Minepacks] Finished loading item translations for 828 items. [02:26:46 INFO]: Minepacks reloaded!

### ISSUE THREAD

**Issue by ngocntpvn** [GeorgH93/Minepacks#229]
### Information
**Environment information**
*Plugin + server version info*:

```

<!-- Replace this with the output of "/backpack version". You can run the command in your console or as op ingame. -->

```

*Online mode*: 

*BungeeCord*: 

**Server/crash log**

```

<!-- Replace this with your crash log / link to your log file -->

```

**Plugin config (optional)**

```

<!-- Replace this with details about your config -->

```

### Details
**Description**  

**Steps to reproduce**  

**Expected behavior**  

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)

**Comment by ngocntpvn** [comment]
my friend can't use /bp

**Comment by ngocntpvn** [comment]
[02:43:45 ERROR]: [Minepacks] Query: INSERT OR IGNORE INTO `backpack_players` (`name`,`uuid`) VALUES (?,?);
[02:43:45 WARN]: org.sqlite.SQLiteException: [SQLITE_READONLY_DBMOVED]  The database file has been moved since it was opened (attempt to write a readonly database)
[02:43:45 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1030)
[02:43:45 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1042)
[02:43:45 WARN]:        at org.sqlite.core.DB.execute(DB.java:884)
[02:43:45 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:54)
[02:43:45 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[02:43:45 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[02:43:45 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.SQL.runStatement(SQL.java:187)
[02:43:45 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.SQLite.lambda$updatePlayer$0(SQLite.java:129)
[02:43:45 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[02:43:45 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[02:43:45 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[02:43:45 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[02:43:45 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[02:43:45 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[02:43:55 INFO]: EchOp1411 issued server command: /a
[02:44:00 INFO]: EchOp1411 issued server command: /bp
[02:44:00 WARN]: [Minepacks] Failed saving backpack for: EchOp1411 (Unable to get players ID from database)

**Comment by ngocntpvn** [comment]
[02:44:00 WARN]: [Minepacks] Failed saving backpack for: EchOp1411 (Unable to get players ID from database)
[02:44:00 INFO]: [Minepacks] Backup of the backpack has been created: /root/paper1/plugins/Minepacks/backups/EchOp1411_af00d23442a83d64b28397556a0da3d6_1662666240851.backpack

**Comment by GeorgH93** [comment]
Please restart your server. Your database file has been moved/deleted after the plugin has been initialized.
