### ISSUE TITLE
Minepacks Being Disabled on startup

### ISSUE THREAD

**Issue by MattDeWeerd** [GeorgH93/Minepacks#272]
### Information
**Environment information**
*Plugin + server version info*:
Cannot do /backpack version. The plugin does not load
```

Cannot do /backpack version. The plugin does not load

```

*Online mode*: yes

*BungeeCord*: no

**Server/crash log**

```

<!-- Replace this with your crash log / link to your log file -->
[11:19:51] [Server thread/INFO]: [Minepacks] PCGF-PluginLib installed. Switching to normal mode!
[11:19:51] [Server thread/WARN]: [Minepacks] Loading Paper plugin in the legacy plugin loading logic. This is not recommended and may introduce some differences into load order. It's highly recommended you move away from this if you are wanting to use Paper plugins.
[11:19:54] [Server thread/INFO]: [Minepacks] Loading server plugin Minepacks v2.4.21.1

[11:20:10] [Server thread/INFO]: [Minepacks] Enabling Minepacks v2.4.21.1
[11:20:10] [Server thread/INFO]: [Minepacks] [32mConfig file successfully loaded.[0m
[11:20:10] [Server thread/INFO]: [Minepacks] [32mLanguage file successfully loaded. Language: english  Author: GeorgH93[0m
[11:20:10] [Server thread/INFO]: [at.pcgf.libs.com.zaxxer.hikari.HikariDataSource] Minepacks-Connection-Pool - Starting...
[11:20:10] [Server thread/INFO]: [at.pcgf.libs.com.zaxxer.hikari.HikariDataSource] Minepacks-Connection-Pool - Start completed.
[11:20:10] [Server thread/ERROR]: Error occurred while enabling Minepacks v2.4.21.1 (Is it up to date?)
java.lang.NoSuchMethodError: 'at.pcgamingfreaks.Message.Message at.pcgamingfreaks.Bukkit.Message.Message.staticPlaceholder(java.lang.String, at.pcgamingfreaks.Message.Placeholder.Processors.IPlaceholderProcessor, java.lang.Object)'
	at at.pcgamingfreaks.Minepacks.Bukkit.Command.OpenCommand.<init>(OpenCommand.java:51) ~[Minepacks.jar:?]
	at at.pcgamingfreaks.Minepacks.Bukkit.Command.CommandManager.<init>(CommandManager.java:75) ~[Minepacks.jar:?]
	at at.pcgamingfreaks.Minepacks.Bukkit.Minepacks.load(Minepacks.java:204) ~[Minepacks.jar:?]
	at at.pcgamingfreaks.Minepacks.Bukkit.Minepacks.onEnable(Minepacks.java:119) ~[Minepacks.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-"483368e"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-"483368e"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.4.jar:git-Paper-"483368e"]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.19.4.jar:git-Paper-"483368e"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-"483368e"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-"483368e"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-"483368e"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-"483368e"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-"483368e"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[11:20:10] [Server thread/INFO]: [Minepacks] Disabling Minepacks v2.4.21.1
[11:20:11] [Server thread/INFO]: [at.pcgf.libs.com.zaxxer.hikari.HikariDataSource] Minepacks-Connection-Pool - Shutdown initiated...
[11:20:11] [Server thread/INFO]: [at.pcgf.libs.com.zaxxer.hikari.HikariDataSource] Minepacks-Connection-Pool - Shutdown completed.
[11:20:11] [Server thread/INFO]: [Minepacks] [31m Minepacks has been disabled. [33m :( [0m

```

**Plugin config (optional)**

```

<!-- Replace this with details about your config -->

```

### Details
**Description**  
Launching the server causes the plugin to disable. It worked fine yesterday but I think after the auto update, it broke

**Steps to reproduce**  
Launch the server

**Expected behavior**  
Expect the plugin to load and function

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)

**Comment by GeorgH93** [comment]
Looks like you are using an outdated version of PCGF PluginLib, please make sure you are on the [latest build](https://ci.pcgamingfreaks.at/job/PluginLib/741/artifact/target/PCGF_PluginLib-1.0.39-SNAPSHOT.jar).

**Comment by MattDeWeerd** [comment]
I am already running PCGF_PluginLib-1.0.39-SNAPSHOT.jar

**Comment by GeorgH93** [comment]
Please try if [this version of Minepacks](https://ci.pcgamingfreaks.at/job/Minepacks/352/artifact/a/Minepacks-2.4.22-SNAPSHOT-Release.jar) together with [this version of PCGF_PluginLib](https://ci.pcgamingfreaks.at/job/PluginLib/743/artifact/target/PCGF_PluginLib-1.0.39.1-SNAPSHOT.jar) works for you.

**Comment by MattDeWeerd** [comment]
I had regotten the same versions I had of both and seemed to fix it. Maybe something broke in the auto-update of minepacks
