### ISSUE TITLE
[Minepacks] Query: UPDATE `backpack_players` SET `name`=? WHERE `uuid`=?;

### ISSUE THREAD

**Issue by Danila767** [GeorgH93/Minepacks#279]
```
[21:00:22 ERROR]: [Minepacks] Query: UPDATE `backpack_players` SET `name`=? WHERE `uuid`=?;
[21:00:22 WARN]: java.sql.SQLTransientConnectionException: Minepacks-Connection-Pool - Connection is not available, request timed out after 30000ms.
[21:00:22 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
[21:00:22 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
[21:00:22 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
[21:00:22 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[21:00:22 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Database.ConnectionProvider.PooledConnectionProvider.getConnection(PooledConnectionProvider.java:74)
[21:00:22 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.SQL.getConnection(SQL.java:124)
[21:00:22 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.SQL.runStatement(SQL.java:179)
[21:00:22 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.SQLite.lambda$updatePlayer$0(SQLite.java:129)
[21:00:22 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[21:00:22 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[21:00:22 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:00:22 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[21:00:22 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[21:00:22 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[21:00:23 WARN]: [Minepacks] Failed to save backpack in database! Error: Minepacks-Connection-Pool - Connection is not available, request timed out after 30000ms.
[21:00:23 WARN]: java.sql.SQLTransientConnectionException: Minepacks-Connection-Pool - Connection is not available, request timed out after 30000ms.
[21:00:23 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
[21:00:23 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
[21:00:23 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
[21:00:23 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[21:00:23 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Database.ConnectionProvider.PooledConnectionProvider.getConnection(PooledConnectionProvider.java:74)
[21:00:23 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.SQL.getConnection(SQL.java:124)
[21:00:23 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.SQL.lambda$saveBackpack$2(SQL.java:209)
[21:00:23 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[21:00:23 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[21:00:23 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:00:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[21:00:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[21:00:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

 ##### Start Minepacks version info #####
 Minepacks: 2.4.22-T20230821225128
 Server: git-Pufferfish-27 (MC: 1.20.1)
 Java: 18.0.2.1
 #####  End Minepacks version info  #####
 
**This happened for the first time in many months of using the plugin, the server crashed and after restarting everything started working normally**

**Comment by GeorgH93** [comment]
Your database is not available for some reason.
