### ISSUE TITLE
WARN]: java.lang.NoSuchFieldException: DECORATED_POT

### ISSUE THREAD

**Issue by jonjbm** [GeorgH93/Minepacks#294]
### Information
**Environment information**
*Plugin + server version info*:

```
[17:39:42 INFO]: ##### Start Minepacks version info #####
[17:39:42 INFO]: Minepacks: 2.4.24-T20231206015532
[17:39:42 INFO]: Server: git-Paper-378 (MC: 1.20.4)
[17:39:42 INFO]: Java: 21.0.1
[17:39:42 INFO]: #####  End Minepacks version info  #####
```

*Online mode*: Yes

*BungeeCord*: No

**Server/crash log**

```
[17:27:14 WARN]: java.lang.NoSuchFieldException: DECORATED_POT
[17:27:14 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2782)
[17:27:14 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Reflection.getField(Reflection.java:208)
[17:27:14 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Bukkit.NMSReflectionRemapped.getNmsField(NMSReflectionRemapped.java:126)
[17:27:14 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Bukkit.Util.InventoryTypeMapper_Reflection.<clinit>(InventoryTypeMapper_Reflection.java:54)
[17:27:14 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Bukkit.Util.InventoryUtils_1_20_R3.updateInventoryTitlePrepared(InventoryUtils_1_20_R3.java:71)
[17:27:14 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Bukkit.Util.InventoryUtils_1_20_R3.openInventoryWithCustomTitlePrepared(InventoryUtils_1_20_R3.java:93)
[17:27:14 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Bukkit.Util.InventoryUtils.openInventoryWithCustomTitlePrepared(InventoryUtils.java:240)
[17:27:14 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.Bukkit.Backpack.open(Backpack.java:156)
[17:27:14 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.Bukkit.Minepacks.openBackpack(Minepacks.java:354)
[17:27:14 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.Bukkit.Minepacks$1.onResult(Minepacks.java:322)
[17:27:14 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.Bukkit.Minepacks$1.onResult(Minepacks.java:318)
[17:27:14 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.Database.getBackpack(Database.java:238)
[17:27:14 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.Database.getBackpack(Database.java:244)
[17:27:14 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.Bukkit.Minepacks.openBackpack(Minepacks.java:317)
[17:27:14 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.Bukkit.Minepacks.openBackpack(Minepacks.java:305)
[17:27:14 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.Bukkit.Command.OpenCommand.execute(OpenCommand.java:80)
[17:27:14 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.Bukkit.Command.OpenCommand.execute(OpenCommand.java:39)
[17:27:14 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.Bukkit.API.MinepacksCommand.doExecute(MinepacksCommand.java:124)
[17:27:14 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.Bukkit.API.MinepacksCommand.doExecute(MinepacksCommand.java:37)
[17:27:14 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Bukkit.Command.CommandExecutorWithSubCommandsGeneric.onCommand(CommandExecutorWithSubCommandsGeneric.jav
a:39)
[17:27:14 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.Bukkit.Command.CommandManager.onCommand(CommandManager.java:118)
[17:27:14 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Bukkit.Command.RegisterablePluginCommand.execute(RegisterablePluginCommand.java:157)
[17:27:14 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[17:27:14 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:987)
[17:27:14 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer.performCommand(CraftPlayer.java:716)
[17:27:14 WARN]:        at Minepacks.jar//at.pcgamingfreaks.MinepacksStandalone.Bukkit.Listener.ItemShortcut.onItemInteract(ItemShortcut.java:185)
[17:27:14 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor265.execute(Unknown Source)
[17:27:14 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[17:27:14 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[17:27:14 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:27:14 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[17:27:14 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[17:27:14 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[17:27:14 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:592)
[17:27:14 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549)
[17:27:14 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543)
[17:27:14 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:539)
[17:27:14 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1997)
[17:27:14 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:32)
[17:27:14 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:8)
[17:27:14 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:54)
[17:27:14 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:27:14 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[17:27:14 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[17:27:14 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1458)
[17:27:14 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[17:27:14 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[17:27:14 WARN]:        at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1435)
[17:27:14 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1358)
[17:27:14 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[17:27:14 WARN]:        at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1336)
[17:27:14 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1220)
[17:27:14 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[17:27:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Details
**Description**  
This warning always pops up the first time someone opens their backpack in their current session. Subsequent openings in the same session do not trigger it, only the first time opening it in the session.

**Steps to reproduce**  
Join the server and open your backpack.

**Expected behavior**  
Not having a giant warning message printed out in my CLI.

**Comment by GeorgH93** [comment]
Should be fixed with [v2.4.25](https://github.com/GeorgH93/Minepacks/releases/tag/v2.4.25)
