### ISSUE TITLE
Plugin incompatible with Paper based servers running 1.20.5 and 1.20.6

### ISSUE THREAD

**Issue by theoneinblack04** [GeorgH93/Minepacks#315]
### Information
**Environment information**
*Plugin + server version info*:

```

<!-- Replace this with the output of "/backpack version". You can run the command in your console or as op ingame. -->

```

*Online mode*: 

*BungeeCord*: 

**Server/crash log**

```

<!-- Replace this with your crash log / link to your log file -->

```

**Plugin config (optional)**

```

<!-- Replace this with details about your config -->

```

### Details
**Description**  

**Steps to reproduce**  

**Expected behavior**  

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)

**Comment by GeorgH93** [comment]
Please update the plugin to the [latest version](https://github.com/GeorgH93/Minepacks/releases/tag/v2.4.28).

**Comment by theoneinblack04** [comment]
I have updated to the latest version and still have the same issue.

I have also tried installing the plugin on a Paper Server without success.

**Comment by JuergenUniVie** [comment]
Minepacks does not start under 1.20.6

[09:49:07] [Server thread/INFO]: [Minepacks] Enabling Minepacks v2.4.28-T20240424192353
[09:49:07] [Server thread/INFO]: [Minepacks] Starting Minepacks in standalone mode!
[09:49:07] [Server thread/ERROR]: [Minepacks] Failed to load config file!
at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.yaml.YamlInvalidContentException: Unexpected end of file! Quoted string value started (87), but has no end!
	at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.yaml.YamlReader.process(YamlReader.java:85) ~[Minepacks.jar:?]
	at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.yaml.YAML.load(YAML.java:142) ~[Minepacks.jar:?]
	at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.yaml.YAML.load(YAML.java:124) ~[Minepacks.jar:?]
	at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.yaml.YAML.load(YAML.java:67) ~[Minepacks.jar:?]
	at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.yaml.YAML.<init>(YAML.java:31) ~[Minepacks.jar:?]
	at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Config.YamlFileManager.load(YamlFileManager.java:248) ~[Minepacks.jar:?]
	at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Config.Configuration.<init>(Configuration.java:76) ~[Minepacks.jar:?]
	at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Config.Configuration.<init>(Configuration.java:68) ~[Minepacks.jar:?]
	at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Config.Configuration.<init>(Configuration.java:57) ~[Minepacks.jar:?]
	at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Config.Configuration.<init>(Configuration.java:47) ~[Minepacks.jar:?]
	at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.Config.<init>(Config.java:48) ~[Minepacks.jar:?]
	at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.Bukkit.Minepacks.onEnable(Minepacks.java:112) ~[Minepacks.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:git-Paper-72]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:git-Paper-72]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:609) ~[paper-1.20.6.jar:git-Paper-72]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:558) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:681) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-72]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[09:49:07] [Server thread/ERROR]: Error occurred while enabling Minepacks v2.4.28-T20240424192353 (Is it up to date?)
at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Config.Configuration$ConfigNotInitializedException: The config file has not been loaded successful
	at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Config.Configuration.getConfigE(Configuration.java:108) ~[Minepacks.jar:?]
	at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.Config.getUpdateChannel(Config.java:226) ~[Minepacks.jar:?]
	at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.Bukkit.Minepacks.onEnable(Minepacks.java:113) ~[Minepacks.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:git-Paper-72]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:git-Paper-72]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:609) ~[paper-1.20.6.jar:git-Paper-72]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:558) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:681) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-72]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[09:49:07] [Server thread/INFO]: [Minepacks] Disabling Minepacks v2.4.28-T20240424192353
[09:49:07] [Server thread/INFO]: [Minepacks]  Minepacks has been disabled.  :(

**Comment by GeorgH93** [comment]
> I have updated to the latest version and still have the same issue.
> 
> I have also tried installing the plugin on a Paper Server without success.

In that case please share your log.




> Minepacks does not start under 1.20.6
> 
> [09:49:07] [Server thread/INFO]: [Minepacks] Enabling Minepacks v2.4.28-T20240424192353 [09:49:07] [Server thread/INFO]: [Minepacks] Starting Minepacks in standalone mode! [09:49:07] [Server thread/ERROR]: [Minepacks] Failed to load config file! at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.yaml.YamlInvalidContentException: Unexpected end of file! Quoted string value started (87), but has no end! at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.yaml.YamlReader.process(YamlReader.java:85) ~[Minepacks.jar:?] at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.yaml.YAML.load(YAML.java:142) ~[Minepacks.jar:?] at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.yaml.YAML.load(YAML.java:124) ~[Minepacks.jar:?] at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.yaml.YAML.load(YAML.java:67) ~[Minepacks.jar:?] at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.yaml.YAML.(YAML.java:31) ~[Minepacks.jar:?] at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Config.YamlFileManager.load(YamlFileManager.java:248) ~[Minepacks.jar:?] at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Config.Configuration.(Configuration.java:76) ~[Minepacks.jar:?] at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Config.Configuration.(Configuration.java:68) ~[Minepacks.jar:?] at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Config.Configuration.(Configuration.java:57) ~[Minepacks.jar:?] at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Config.Configuration.(Configuration.java:47) ~[Minepacks.jar:?] at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.Config.(Config.java:48) ~[Minepacks.jar:?] at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.Bukkit.Minepacks.onEnable(Minepacks.java:112) ~[Minepacks.jar:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:git-Paper-72] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:git-Paper-72] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?] at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:609) ~[paper-1.20.6.jar:git-Paper-72] at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:558) ~[paper-1.20.6.jar:git-Paper-72] at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:681) ~[paper-1.20.6.jar:git-Paper-72] at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[paper-1.20.6.jar:git-Paper-72] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:git-Paper-72] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[paper-1.20.6.jar:git-Paper-72] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-72] at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?] [09:49:07] [Server thread/ERROR]: Error occurred while enabling Minepacks v2.4.28-T20240424192353 (Is it up to date?) at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Config.Configuration$ConfigNotInitializedException: The config file has not been loaded successful at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Config.Configuration.getConfigE(Configuration.java:108) ~[Minepacks.jar:?] at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.Config.getUpdateChannel(Config.java:226) ~[Minepacks.jar:?] at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.Bukkit.Minepacks.onEnable(Minepacks.java:113) ~[Minepacks.jar:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:git-Paper-72] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:git-Paper-72] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?] at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:609) ~[paper-1.20.6.jar:git-Paper-72] at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:558) ~[paper-1.20.6.jar:git-Paper-72] at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:681) ~[paper-1.20.6.jar:git-Paper-72] at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[paper-1.20.6.jar:git-Paper-72] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:git-Paper-72] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[paper-1.20.6.jar:git-Paper-72] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-72] at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?] [09:49:07] [Server thread/INFO]: [Minepacks] Disabling Minepacks v2.4.28-T20240424192353 [09:49:07] [Server thread/INFO]: [Minepacks] Minepacks has been disabled. :(

Line 87 of the config is invalid (should be your db password, please ensure it's a valid yaml string there.

**Comment by JuergenUniVie** [comment]
indeed, typo error but won't start - it's just a 1.20.6 testserver so no stress from my side....) just to keep you informed

[10:32:38] [Server thread/ERROR]: Error occurred while enabling Minepacks v2.4.28-T20240424192353 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.Bukkit.Minepacks.warnOnVersionIncompatibility(Minepacks.java:277) ~[Minepacks.jar:?]
	at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.Bukkit.Minepacks.checkMcVersion(Minepacks.java:128) ~[Minepacks.jar:?]
	at Minepacks.jar/at.pcgamingfreaks.MinepacksStandalone.Bukkit.Minepacks.onEnable(Minepacks.java:116) ~[Minepacks.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:git-Paper-72]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:git-Paper-72]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:609) ~[paper-1.20.6.jar:git-Paper-72]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:558) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:681) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-72]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[10:32:38] [Server thread/INFO]: [Minepacks] Disabling Minepacks v2.4.28-T20240424192353
[10:32:38] [Server thread/INFO]: [Minepacks]  Minepacks has been disabled.  :(

**Comment by theoneinblack04** [comment]
This is my log:

[20:32:03 WARN]: [Minepacks] ################################
[20:32:03 ERROR]: Error occurred while enabling Minepacks v2.4.28-T20240424192018 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at Minepacks-2.4.28.jar/at.pcgamingfreaks.Minepacks.Bukkit.Minepacks.warnOnVersionIncompatibility(Minepacks.java:269) ~[Minepacks-2.4.28.jar:?]
        at Minepacks-2.4.28.jar/at.pcgamingfreaks.Minepacks.Bukkit.Minepacks.checkMcVersion(Minepacks.java:126) ~[Minepacks-2.4.28.jar:?]
        at Minepacks-2.4.28.jar/at.pcgamingfreaks.Minepacks.Bukkit.Minepacks.onEnable(Minepacks.java:114) ~[Minepacks-2.4.28.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:git-Paper-71]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:git-Paper-71]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:609) ~[paper-1.20.6.jar:git-Paper-71]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:558) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:681) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-71]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[20:32:03 INFO]: [Minepacks] Disabling Minepacks v2.4.28-T20240424192018
[20:32:03 INFO]: [Minepacks]  Minepacks has been disabled.  :(

**Comment by GeorgH93** [comment]
Looks like you are using paper. Since they decided to change stuff again, you will have to wait until I have time to add support for this.
You can use Spigot meanwhile.

**Comment by LucidAPs** [comment]
Please add support for paper servers.
