### ISSUE TITLE
V1.19.3 to V2.0.3 error - paper-1.14.2

### ISSUE THREAD

**Issue by mcpanglei** [GeorgH93/Minepacks#39]
[11:17:06] [Server thread/INFO]: [Minepacks] Enabling Minepacks v2.0.3-Release
[11:17:06] [Server thread/INFO]: [Minepacks] Starting Minepacks in standalone mode!
[11:17:06] [Server thread/INFO]: [Minepacks] [32mConfig file successfully loaded.[0m
[11:17:06] [Server thread/INFO]: [Minepacks] [32mLanguage file successfully loaded. Language: english  Author: GeorgH93[0m
[11:17:06] [Server thread/INFO]: [at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.HikariDataSource] Minepacks-Connection-Pool - Starting...
[11:17:06] [Server thread/INFO]: [at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.HikariDataSource] Minepacks-Connection-Pool - Start completed.
[11:17:06] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Key column 'uuid' doesn't exist in table
[11:17:06] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[11:17:06] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[11:17:06] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[11:17:06] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[11:17:06] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[11:17:06] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[11:17:06] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[11:17:06] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
[11:17:06] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[11:17:06] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
[11:17:06] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
[11:17:06] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491)
[11:17:06] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1552)
[11:17:06] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2607)
[11:17:06] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1480)
[11:17:06] [Server thread/WARN]: 	at at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:120)
[11:17:06] [Server thread/WARN]: 	at at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java)
[11:17:06] [Server thread/WARN]: 	at at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Database.SQLTableValidator.validate(SQLTableValidator.java:93)
[11:17:06] [Server thread/WARN]: 	at at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Database.DBTools.updateDB(DBTools.java:58)
[11:17:06] [Server thread/WARN]: 	at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.MySQL.checkDB(MySQL.java:59)
[11:17:06] [Server thread/WARN]: 	at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.SQL.<init>(SQL.java:59)
[11:17:06] [Server thread/WARN]: 	at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.MySQL.<init>(MySQL.java:36)
[11:17:06] [Server thread/WARN]: 	at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.Database.getDatabase(Database.java:111)
[11:17:06] [Server thread/WARN]: 	at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Minepacks.load(Minepacks.java:189)
[11:17:06] [Server thread/WARN]: 	at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Minepacks.onEnable(Minepacks.java:147)
[11:17:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:17:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[11:17:06] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[11:17:06] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464)
[11:17:06] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378)
[11:17:06] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:465)
[11:17:06] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280)
[11:17:06] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:856)
[11:17:06] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:17:06] [Server thread/INFO]: [Minepacks] [32mItem name language file successfully loaded. Language: english  Author: GeorgH93[0m
[11:17:06] [Server thread/INFO]: [Minepacks] Loading item translations ...
[11:17:06] [Server thread/INFO]: [Minepacks] Finished loading item translations for 830 items.
[11:17:06] [Server thread/INFO]: [Minepacks] [32m Minepacks has been enabled! [33m :) [0m

**Comment by GeorgH93** [comment]
This should fix the problem: https://github.com/GeorgH93/Minepacks/releases/download/v2.0.4/Minepacks-2.0.4-Release.jar

**Comment by mcpanglei** [comment]
**the first time load:**
[21:31:39 INFO]: [Minepacks] Enabling Minepacks v2.0.4-Release
[21:31:39 INFO]: [Minepacks] Starting Minepacks in standalone mode!
[21:31:39 INFO]: [Minepacks] Config file successfully loaded.
[21:31:39 INFO]: [Minepacks] Language file successfully loaded. Language: english  Author: GeorgH93
[21:31:39 INFO]: [at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.HikariDataSource] Minepacks-Connection-Pool - Starting...
[21:31:39 INFO]: [at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.HikariDataSource] Minepacks-Connection-Pool - Start completed.
[21:31:40 WARN]: java.sql.SQLException: Cannot add foreign key constraint
[21:31:40 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[21:31:40 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
[21:31:40 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[21:31:40 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
[21:31:40 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
[21:31:40 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491)
[21:31:40 WARN]:        at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1552)
[21:31:40 WARN]:        at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2607)
[21:31:40 WARN]:        at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1480)
[21:31:40 WARN]:        at at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:120)
[21:31:40 WARN]:        at at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java)
[21:31:40 WARN]:        at at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Database.SQLTableValidator.validate(SQLTableValidator.java:93)
[21:31:40 WARN]:        at at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Database.DBTools.updateDB(DBTools.java:58)
[21:31:40 WARN]:        at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.MySQL.checkDB(MySQL.java:66)
[21:31:40 WARN]:        at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.SQL.<init>(SQL.java:59)
[21:31:40 WARN]:        at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.MySQL.<init>(MySQL.java:36)
[21:31:40 WARN]:        at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.Database.getDatabase(Database.java:111)
[21:31:40 WARN]:        at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Minepacks.load(Minepacks.java:189)
[21:31:40 WARN]:        at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Minepacks.onEnable(Minepacks.java:147)
[21:31:40 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:31:40 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[21:31:40 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[21:31:40 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464)
[21:31:40 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378)
[21:31:40 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:465)
[21:31:40 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280)
[21:31:40 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:856)
[21:31:40 WARN]:        at java.lang.Thread.run(Thread.java:748)
[21:31:40 WARN]: [Minepacks] Failed to extract file "/lang/items_chs.yml"!
[21:31:40 INFO]: [Minepacks] File "/lang/items_en.yml" extracted successfully!
[21:31:40 INFO]: [Minepacks] Item name language file successfully loaded. Language: english  Author: GeorgH93
[21:31:40 INFO]: [Minepacks] Loading item translations ...
[21:31:40 INFO]: [Minepacks] Finished loading item translations for 830 items.
[21:31:40 INFO]: [Minepacks]  Minepacks has been enabled!  :) 

**the second time load:**
[21:33:06 INFO]: [Minepacks] Enabling Minepacks v2.0.4-Release
[21:33:06 INFO]: [Minepacks] Starting Minepacks in standalone mode!
[21:33:06 INFO]: [Minepacks] Config file successfully loaded.
[21:33:06 INFO]: [Minepacks] Language file successfully loaded. Language: english  Author: GeorgH93
[21:33:06 INFO]: [at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.HikariDataSource] Minepacks-Connection-Pool - Starting...
[21:33:07 INFO]: [at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.HikariDataSource] Minepacks-Connection-Pool - Start completed.
[21:33:07 WARN]: java.sql.SQLException: Cannot add foreign key constraint
[21:33:07 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[21:33:07 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
[21:33:07 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[21:33:07 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
[21:33:07 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
[21:33:07 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491)
[21:33:07 WARN]:        at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1552)
[21:33:07 WARN]:        at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2607)
[21:33:07 WARN]:        at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1480)
[21:33:07 WARN]:        at at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:120)
[21:33:07 WARN]:        at at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java)
[21:33:07 WARN]:        at at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Database.SQLTableValidator.validate(SQLTableValidator.java:93)
[21:33:07 WARN]:        at at.pcgamingfreaks.MinepacksStandalone.libs.at.pcgamingfreaks.Database.DBTools.updateDB(DBTools.java:58)
[21:33:07 WARN]:        at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.MySQL.checkDB(MySQL.java:66)
[21:33:07 WARN]:        at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.SQL.<init>(SQL.java:59)
[21:33:07 WARN]:        at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.MySQL.<init>(MySQL.java:36)
[21:33:07 WARN]:        at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.Database.getDatabase(Database.java:111)
[21:33:07 WARN]:        at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Minepacks.load(Minepacks.java:189)
[21:33:07 WARN]:        at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Minepacks.onEnable(Minepacks.java:147)
[21:33:07 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:33:07 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[21:33:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[21:33:07 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464)
[21:33:07 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378)
[21:33:07 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:465)
[21:33:07 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280)
[21:33:07 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:856)
[21:33:07 WARN]:        at java.lang.Thread.run(Thread.java:748)
[21:33:07 INFO]: [Minepacks] Item name language file successfully loaded. Language: english  Author: GeorgH93
[21:33:07 INFO]: [Minepacks] Loading item translations ...
[21:33:07 INFO]: [Minepacks] Finished loading item translations for 830 items.
[21:33:07 INFO]: [Minepacks]  Minepacks has been enabled!  :)

**Comment by mcpanglei** [comment]
Although there is an error reported above, the original data can be loaded.

**Comment by GeorgH93** [comment]
The error should not cause problems as long as you are not using the cooldown sync feature.
It should be fixed with this release: https://github.com/GeorgH93/Minepacks/releases/download/v2.0.5/Minepacks-2.0.5-Release.jar

**Comment by mcpanglei** [comment]
Great. The problem has been solved.
