### ISSUE TITLE
Mysql problem

### ISSUE THREAD

**Issue by codereese** [GeorgH93/Minepacks#42]
The console will report an error when the player opens the backpack, and there will be duplicate usernames in the database.

[00:29:17 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2' for key 'PRIMARY'
[00:29:17 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[00:29:17 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[00:29:17 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[00:29:17 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[00:29:17 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[00:29:17 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:408)
[00:29:17 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
[00:29:17 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[00:29:17 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[00:29:17 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[00:29:17 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[00:29:17 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
[00:29:17 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[00:29:17 WARN]:        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
[00:29:17 WARN]:        at at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[00:29:17 WARN]:        at at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[00:29:17 WARN]:        at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.SQL.runStatement(SQL.java:272)
[00:29:17 WARN]:        at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.SQL.lambda$runStatementAsync$0(SQL.java:261)
[00:29:17 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[00:29:17 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[00:29:17 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[00:29:17 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[00:29:17 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[00:29:17 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by codereese** [comment]
I use 2.0.6

**Comment by GeorgH93** [comment]
Please provide me with your config (remove the database user and password before uploading it)

**Comment by codereese** [comment]
`# Minepacks Config File

# Language Settings
Language:
  # Defines the used language and the corresponding file used. The corresponding language file will be placed in the lang folder next to the config.yml named: <Language>.yml
  Language: chs
  # Options:
  #     Overwrite (deletes all changes from the file and extracts a new language file)
  #     Upgrade (extracts a new language file and copy's all settings from the old language file)
  #     Update (adds the default (english) text values for all missing values, just some basic formatting)
  UpdateMode: Upgrade

# Title to be shown for the opened inventory for everyone except the owner of the backpack. Can contain {OwnerName} (which will be replaced with the players name).
BackpackTitleOther: "&b{OwnerName}的背包"
# The title of the inventory for the owner of the backpack.
BackpackTitle: "&e&l次元背包-可跨服"
# Defines if the content of the backpack get dropped on the death of a player.
# If enabled, it can be disabled for individual players with the "backpack.KeepOnDeath" permission.
DropOnDeath: false
# Defines the max amount of columns for a backpack.
# The size of the user's backpack will be defined by the permission, permissions for bigger backpacks than this value will be ignored.
# Can be set to anything > 0. Backpacks with more than 6 columns will have a broken UI! Sizes bigger than 9 may not work with all permission plugins.
MaxSize: 6
# Defines in which game-modes a player can access his backpack (name or id)
# Options: ADVENTURE, CREATIVE, SPECTATOR, SURVIVAL
# AllowedGameModes: [ "SURVIVAL", "ADVENTURE" ]
AllowedGameModes: [ "SURVIVAL" ]

Cooldown:
  # Defines how long a player have to wait till he can reopen his backpack.
  # Time is in seconds. Values < 1 disable the cooldown.
  Command: 10
  # If enabled, cooldowns will be synced between servers (BungeeCord network). It will also allow to keep cooldown through server restarts.
  # You should only use it with long cooldown times.
  Sync: true
  AddOnJoin: true
  # You can turn this on when using sync to reduce the memory consumption a little bit
  ClearOnLeave: true
  # Removes old cooldowns from the cache to free memory. Time in seconds.
  CleanupInterval: 600

# Controls for the auto pickup on full inventory function
FullInventory:
  # If items should be collected to the backpack if the players inventory is full
  CollectItems: false
  # Interval in seconds how often items around the player should be collected, increase it if it lags the server
  CheckInterval: 1
  # Radius in which items get collected, in meter/blocks, allow decimals
  CollectRadius: 1.5


# Database settings
Database:
  # Database type. MySQL, SQLite or Files
  Type: MySQL
  # Turn off if you want to use player ids created from an other plugin. When using shared tables please check the tables selection
  UpdatePlayer: false
  # Auto database cleanup settings
  AutoCleanup:
    # Defines the max amount of days backpacks will be stored. -1 to disable auto cleanup
    MaxInactiveDays: -1
  # If you would like to use UUIDs, it is recommended not to change this setting unless you know what you are doing!
  # true: Should be used if your server is running Minecraft 1.7.5 or newer
  # false: In offline mode or for minecraft version below 1.7.5
  # If you are using BungeeCord please set this setting based on your BungeeCord's online mode!!!
  UseUUIDs: true
  # Defines the storage format for UUIDs for compatibility with other plugins (shared tables)
  # true: format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  # false: format: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  UseUUIDSeparators: true
  # Settings only for MySQL
  SQL:
    Host: localhost:3306
    Database: a
    User: a
    Password: a
    # The max amount of connections to the database the connection pool will open
    MaxConnections: 4
    # List of properties for your SQL connection. Can be used to disable SSL.
    # Properties: ["useSSL=false"]
    Properties: []
  # Tables settings for shared tables when using MySQL - Advanced MySQL Settings
  # Use these settings only if you know what you are doing!!!!
  # Do only change this settings if you know what you are doing and have some basic MySQL knowledge!!!
  # Changing settings down here after you have used this plugin may result in data inconsistency!!!
  Tables:
    # Table names
    # Don't change the players table if you have backpacks stored in your database already! Player id's might wont match anymore resulting data inconsistency.
    User: backpack_players
    Backpack: backpacks
    Cooldown: backpack_cooldowns
    # Field settings for the tables
    # Do not change them after the tables have been generated!
    # If you like to change them after the tables have been generated alter the tables manually or delete them (the system then will regenerate them).
    Fields:
      User:
        Player_ID: player_id
        Name: name
        UUID: uuid
      Backpack:
        Owner_ID: owner
        ItemStacks: itemstacks
        Version: version
        LastUpdate: lastupdate
      Cooldown:
        Player_ID: id
        Time: time
  # Settings controlling the cache behavior of the plugin. You may can optimize it a little bit depending on your player count, ram or cpu bottlenecks.
  Cache:
    UnCache:
      # The strategie used to uncache offline players. Options
      #     interval (offline players get uncached every x seconds)
      #     intervalChecked (like interval, but also ensures that the player is already offline for at least the interval time, add's a cpu overhead)
      #     ondisconnect (player instantly gets uncached as soon as he disconnects, may adds overhead if other plugins try to access the player data when they go offline, also it may be problematic for players with unstable connections)
      #     ondisconnectdelayed (player gets uncached x seconds after he went offline, adds overhead on disconnect, you shouldn't use this with a lot of players joining and leaving.)
      Strategie: ondisconnect
      # Used for the interval based uncaching algorithms. Also used as delay for ondisconnectdelayed. Value in seconds. Default: 600 = 10 minutes
      Interval: 600
      Delay: 600

Shulkerboxes:
  # This setting controls whether players can put shulkerboxes into their backpacks.
  PreventInBackpack: true
  # This setting allows to disable shulkerboxes all together. Players won't be able to craft or use them.
  DisableShulkerboxes: false
  # This settings controls how existing shulkerboxes are handled if they are disabled.
  # Options: Ignore, Remove = shulker-box will be removed including it's content, Destroy = shulker-box will be destroyed and it's content will be dropped
  Existing: "Ignore"

ItemFilter:
  # Enables the item filter. Make sure to define items to be filtered.
  Enable: false
  # List off items not allowed in the backpack. Can be name or id (id only for MC versions older than 1.13!).
  Blacklist: []

# This settings allow control over how the plugin behave in different worlds
WorldSettings:
  # All worlds listed here will not have the plugin usable
  # Blacklist: ["creative_world"]
  # Blacklist: ["creative_world1", "creative_world2"]
  Blacklist: []
  # Defines how the Blacklist will be enforced
  # Options:
  #   Message           = The player will see an message that the usage of the backpack is denied in this world.
  #   MissingPermission = The player will receive the plugins no permission message.
  #   NoPlugin          = The plugin will not be available at all and act as if it was not installed.
  #                       This also exclude players with permission to bypass the world restriction from using it!
  #                       It will not disable the Shulkerboxes filter!
  BlacklistMode: "Message"

Misc:
  # Enables/Disables the auto-update function of the plugin.
  AutoUpdate: false
  # Enable this option if you are using a BungeeCord setup!
  UseBungeeCord: false

# Config file version. Don't touch it!
Version: 21`

**Comment by codereese** [comment]
[config.yml.txt](https://github.com/GeorgH93/Minepacks/files/3355952/config.yml.txt)

**Comment by GeorgH93** [comment]
Can you please provide me with at least 5 more lines of the log right before the error message

**Comment by codereese** [comment]
776 issued server command: /backpack
[00:34:33] [Craft Scheduler Thread - 98/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '95' for key 'PRIMARY'
[00:34:33] [Craft Scheduler Thread - 98/WARN]: 	at sun.reflect.GeneratedConstructorAccessor350.newInstance(Unknown Source)
[00:34:33] [Craft Scheduler Thread - 98/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[00:34:33] [Craft Scheduler Thread - 98/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[00:34:33] [Craft Scheduler Thread - 98/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[00:34:33] [Craft Scheduler Thread - 98/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[00:34:33] [Craft Scheduler Thread - 98/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
[00:34:33] [Craft Scheduler Thread - 98/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[00:34:33] [Craft Scheduler Thread - 98/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[00:34:33] [Craft Scheduler Thread - 98/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[00:34:33] [Craft Scheduler Thread - 98/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[00:34:33] [Craft Scheduler Thread - 98/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
[00:34:33] [Craft Scheduler Thread - 98/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[00:34:33] [Craft Scheduler Thread - 98/WARN]: 	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
[00:34:33] [Craft Scheduler Thread - 98/WARN]: 	at at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[00:34:33] [Craft Scheduler Thread - 98/WARN]: 	at at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[00:34:33] [Craft Scheduler Thread - 98/WARN]: 	at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.SQL.runStatement(SQL.java:272)
[00:34:33] [Craft Scheduler Thread - 98/WARN]: 	at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.SQL.lambda$runStatementAsync$0(SQL.java:261)
[00:34:33] [Craft Scheduler Thread - 98/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[00:34:33] [Craft Scheduler Thread - 98/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[00:34:33] [Craft Scheduler Thread - 98/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[00:34:33] [Craft Scheduler Thread - 98/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[00:34:33] [Craft Scheduler Thread - 98/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[00:34:33] [Craft Scheduler Thread - 98/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[00:34:33] [Server thread/INFO]: <•第一•[SVIP+]sw镇子se商店北北[6]> 商店新上了一批蛋 想要的可以来看看
[00:34:36] [User Authenticator #6/INFO]: UUID of player Xue_ba is 16512ff3-3387-4fcc-a4a3-bd489de2a869
[00:34:36] [Server thread/INFO]: Xue_ba[/110.89.6.19:41534] logged in with entity id 27438 at ([world]-4985.417278471253, 79.0, -5717.4307458960375)
[00:34:36] [Craft Scheduler Thread - 105/INFO]: [云隙] Now Max Player is 80
[00:34:36] [Server thread/INFO]: [云隙] ====================================
[00:34:36] [Server thread/INFO]: [云隙] [会员][VIP]Xue_ba[9]愉快的加入了我们~
[00:34:36] [Server thread/INFO]: [云隙] ====================================
[00:34:37] [Server thread/INFO]: A_Joker issued server command: /hub
[00:34:38] [Server thread/INFO]: 逆光是你哥 issued server command: /tpahere 零
[00:34:39] [Server thread/INFO]: A_Joker lost connection: Disconnected
[00:34:39] [Server thread/INFO]: [云隙] Saved A_Joker Lv0-150-vip1
[00:34:39] [Server thread/INFO]: 穆臣ono issued server command: /w sd
[00:34:39] [Server thread/INFO]: 小航 issued server command: /sell
[00:34:39] [Server thread/INFO]: <☺稚友[4]> 我去
[00:34:40] [Server thread/INFO]: 逆光是你哥 issued server command: /tpahere 零
[00:34:41] [Server thread/INFO]: 穆臣ono issued server command: /w sa
[00:34:41] [Server thread/INFO]: Chris issued server command: /menu
[00:34:42] [Server thread/INFO]: Chris issued server command: /backpack
[00:34:42] [Craft Scheduler Thread - 109/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '73' for key 'PRIMARY'
[00:34:42] [Craft Scheduler Thread - 109/WARN]: 	at sun.reflect.GeneratedConstructorAccessor350.newInstance(Unknown Source)
[00:34:42] [Craft Scheduler Thread - 109/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[00:34:42] [Craft Scheduler Thread - 109/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[00:34:42] [Craft Scheduler Thread - 109/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[00:34:42] [Craft Scheduler Thread - 109/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[00:34:42] [Craft Scheduler Thread - 109/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
[00:34:42] [Craft Scheduler Thread - 109/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[00:34:42] [Craft Scheduler Thread - 109/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[00:34:42] [Craft Scheduler Thread - 109/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[00:34:42] [Craft Scheduler Thread - 109/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[00:34:42] [Craft Scheduler Thread - 109/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
[00:34:42] [Craft Scheduler Thread - 109/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[00:34:42] [Craft Scheduler Thread - 109/WARN]: 	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
[00:34:42] [Craft Scheduler Thread - 109/WARN]: 	at at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[00:34:42] [Craft Scheduler Thread - 109/WARN]: 	at at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[00:34:42] [Craft Scheduler Thread - 109/WARN]: 	at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.SQL.runStatement(SQL.java:272)
[00:34:42] [Craft Scheduler Thread - 109/WARN]: 	at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.SQL.lambda$runStatementAsync$0(SQL.java:261)
[00:34:42] [Craft Scheduler Thread - 109/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[00:34:42] [Craft Scheduler Thread - 109/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[00:34:42] [Craft Scheduler Thread - 109/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[00:34:42] [Craft Scheduler Thread - 109/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[00:34:42] [Craft Scheduler Thread - 109/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[00:34:42] [Craft Scheduler Thread - 109/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[00:34:43] [Server thread/INFO]: 穆臣ono issued server command: /w se
[00:34:44] [Server thread/INFO]: <☺稚友[4]> 咋那么多
[00:34:45] [Server thread/INFO]: 楚江ono issued server command: /hub
[00:34:45] [Server thread/INFO]: 零Zero issued server command: /tpaccept
[00:34:46] [Server thread/INFO]: 北北 issued server command: /see
[00:34:46] [Server thread/INFO]: 楚江ono lost connection: Disconnected
[00:34:46] [Server thread/INFO]: [云隙] Saved 楚江ono Lv7-942-vip1
[00:34:47] [Server thread/INFO]: 776 issued server command: /menu
[00:34:47] [Server thread/INFO]: Xue_ba issued server command: /menu
[00:34:48] [Server thread/INFO]: 776 issued server command: /plot home
[00:34:48] [Server thread/INFO]: Xue_ba issued server command: /backpack
[00:34:48] [Craft Scheduler Thread - 109/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2' for key 'PRIMARY'
[00:34:48] [Craft Scheduler Thread - 109/WARN]: 	at sun.reflect.GeneratedConstructorAccessor350.newInstance(Unknown Source)
[00:34:48] [Craft Scheduler Thread - 109/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[00:34:48] [Craft Scheduler Thread - 109/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[00:34:48] [Craft Scheduler Thread - 109/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[00:34:48] [Craft Scheduler Thread - 109/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[00:34:48] [Craft Scheduler Thread - 109/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
[00:34:48] [Craft Scheduler Thread - 109/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[00:34:48] [Craft Scheduler Thread - 109/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[00:34:48] [Craft Scheduler Thread - 109/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[00:34:48] [Craft Scheduler Thread - 109/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[00:34:48] [Craft Scheduler Thread - 109/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
[00:34:48] [Craft Scheduler Thread - 109/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[00:34:48] [Craft Scheduler Thread - 109/WARN]: 	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
[00:34:48] [Craft Scheduler Thread - 109/WARN]: 	at at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[00:34:48] [Craft Scheduler Thread - 109/WARN]: 	at at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[00:34:48] [Craft Scheduler Thread - 109/WARN]: 	at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.SQL.runStatement(SQL.java:272)
[00:34:48] [Craft Scheduler Thread - 109/WARN]: 	at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.SQL.lambda$runStatementAsync$0(SQL.java:261)
[00:34:48] [Craft Scheduler Thread - 109/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[00:34:48] [Craft Scheduler Thread - 109/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[00:34:48] [Craft Scheduler Thread - 109/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[00:34:48] [Craft Scheduler Thread - 109/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[00:34:48] [Craft Scheduler Thread - 109/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[00:34:48] [Craft Scheduler Thread - 109/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[00:34:52] [Server thread/INFO]: Xue_ba issued server command: /hub
[00:34:53] [Server thread/INFO]: 小航 issued server command: /menu
[00:34:54] [Server thread/INFO]: Xue_ba lost connection: Disconnected

**Comment by codereese** [comment]
I try to change UseUUIDs to false and rebuild the table, but the problem same

**Comment by GeorgH93** [comment]
It is probably caused by the Cooldown.Sync option. Since you add the cooldown to the player when they join the server enabling sync is redundant and you could just disable it.

**Comment by codereese** [comment]
The problem is solved!   Thank you very much!

**Comment by GeorgH93** [comment]
This release should implement a fix for the sync option: https://github.com/GeorgH93/Minepacks/releases/tag/v2.0.7
